package it.engineering.entity;

public enum Qualification {
    DOCTOR_OF_MEDICINE, MEDICAL_ASSISTANT, NURSE_PRACTITIONER, DOCTOR_OF_PHARMACY, CERTIFIED_NURSE_MIDWIFE,
    EMERGENCY_MEDICAL_TECHNICIAN
}
